version: '3'
networks:
  mongo-network:
    name: mongo-network
volumes:
  mongo-data:
    name: mongo-data
services:

  my-app:
    container_name: my-app
    build: .
    image: my-app:to_configure
    ports:
      - 3000:3000
    networks:
      - mongo-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=auth
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
    hostname: mongodb

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
    networks:
      - mongo-network
    hostname: mongo-express
    depends_on:
      - mongodb
